version: '3.4'

services:
  api:
    image: eventhousing
    build: .
    ports:
      - 5000:5000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FLASK_ENV="development"
    depends_on:
      - pg
  pg:
    container_name: event_housing_pg
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: event_housing_db
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
  migration:
    build: .
    command: flask db upgrade
    depends_on:
      - event_housing
